//
// Created by hl on 8/27/18.
//

#ifndef JOYSTICK_JOYSTICKPUBLISHER_H
#define JOYSTICK_JOYSTICKPUBLISHER_H

enum JoystickEvents
{
    JS_EVENT_NEUTRAL,
    JS_EVENT_BUTTON0_DOWN,
    JS_EVENT_BUTTON0_UP,
    JS_EVENT_BUTTON1_DOWN,
    JS_EVENT_BUTTON1_UP,
    JS_EVENT_BUTTON2_DOWN,
    JS_EVENT_BUTTON2_UP,
    JS_EVENT_BUTTON3_DOWN,
    JS_EVENT_BUTTON3_UP,
    JS_EVENT_AXIS_UP,
    JS_EVENT_AXIS_LEFT,
    JS_EVENT_AXIS_RIGHT,
    JS_EVENT_AXIS_DOWN
};

#endif //JOYSTICK_JOYSTICKPUBLISHER_H
