//
// Created by hl on 8/27/18.
//

#ifndef JOYSTICK_JOYSTICKPUBLISHER_H
#define JOYSTICK_JOYSTICKPUBLISHER_H

enum JoystickEvents
{
    JOYSTICK_NEUTRAL,
    JOYSTICK_BUTTON0_DOWN,
    JOYSTICK_BUTTON0_UP,
    JOYSTICK_BUTTON1_DOWN,
    JOYSTICK_BUTTON1_UP,
    JOYSTICK_BUTTON2_DOWN,
    JOYSTICK_BUTTON2_UP,
    JOYSTICK_BUTTON3_DOWN,
    JOYSTICK_BUTTON3_UP,
    JOYSTICK_AXIS_UP,
    JOYSTICK_AXIS_LEFT,
    JOYSTICK_AXIS_RIGHT,
    JOYSTICK_AXIS_DOWN
};

#endif //JOYSTICK_JOYSTICKPUBLISHER_H
