# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from joystick/Joystick.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class Joystick(genpy.Message):
  _md5sum = "053a7b1f7f659589125a990814760aa6"
  _type = "joystick/Joystick"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """time time
int16 value
int8 type
int8 number
"""
  __slots__ = ['time','value','type','number']
  _slot_types = ['time','int16','int8','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       time,value,type,number

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Joystick, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.time is None:
        self.time = genpy.Time()
      if self.value is None:
        self.value = 0
      if self.type is None:
        self.type = 0
      if self.number is None:
        self.number = 0
    else:
      self.time = genpy.Time()
      self.value = 0
      self.type = 0
      self.number = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2Ih2b().pack(_x.time.secs, _x.time.nsecs, _x.value, _x.type, _x.number))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.time is None:
        self.time = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.time.secs, _x.time.nsecs, _x.value, _x.type, _x.number,) = _get_struct_2Ih2b().unpack(str[start:end])
      self.time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2Ih2b().pack(_x.time.secs, _x.time.nsecs, _x.value, _x.type, _x.number))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.time is None:
        self.time = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.time.secs, _x.time.nsecs, _x.value, _x.type, _x.number,) = _get_struct_2Ih2b().unpack(str[start:end])
      self.time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2Ih2b = None
def _get_struct_2Ih2b():
    global _struct_2Ih2b
    if _struct_2Ih2b is None:
        _struct_2Ih2b = struct.Struct("<2Ih2b")
    return _struct_2Ih2b
