(cl:in-package brickpi3_ros-msg)
(cl:export '(HEADER-VAL
          HEADER
          LINEAR_ACCELERATION-VAL
          LINEAR_ACCELERATION
          LINEAR_ACCELERATION_COVARIANCE-VAL
          LINEAR_ACCELERATION_COVARIANCE
))